/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shiping_util_HiResTimer */

#ifndef _Included_com_shiping_util_HiResTimer
#define _Included_com_shiping_util_HiResTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shiping_util_HiResTimer
 * Method:    isHighResTimerAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_shiping_util_HiResTimer_isHighResTimerAvailable
  (JNIEnv *, jobject);

/*
 * Class:     com_shiping_util_HiResTimer
 * Method:    getResolution
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_shiping_util_HiResTimer_getResolution
  (JNIEnv *, jobject);

/*
 * Class:     com_shiping_util_HiResTimer
 * Method:    startTiming
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_shiping_util_HiResTimer_startTiming
  (JNIEnv *, jobject);

/*
 * Class:     com_shiping_util_HiResTimer
 * Method:    endTiming
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_shiping_util_HiResTimer_endTiming
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
